set_false_path -from [get_cells CTRL_s_axi_U/int_Height_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_WidthIn_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_WidthOut_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_PixelRate_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_ColorModeOut_reg[*]]
