-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_3a92_csc_0_v_hcresampler_core_1_Pipeline_VITIS_LOOP_724_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_csc_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_csc_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_csc_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_csc_empty_n : IN STD_LOGIC;
    stream_csc_read : OUT STD_LOGIC;
    stream_out_hresampled_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    stream_out_hresampled_full_n : IN STD_LOGIC;
    stream_out_hresampled_write : OUT STD_LOGIC;
    pixbuf_y_val_V_4 : IN STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_3 : IN STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_2 : IN STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_05241026_lcssa1052_i : IN STD_LOGIC_VECTOR (7 downto 0);
    loopWidth : IN STD_LOGIC_VECTOR (11 downto 0);
    conv2772_cast_cast_i_cast_cast : IN STD_LOGIC_VECTOR (0 downto 0);
    select_ln685 : IN STD_LOGIC_VECTOR (1 downto 0);
    zext_ln720 : IN STD_LOGIC_VECTOR (10 downto 0);
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    pixbuf_y_val_V_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_9_out_ap_vld : OUT STD_LOGIC;
    pixbuf_y_val_V_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_8_out_ap_vld : OUT STD_LOGIC;
    pixbuf_y_val_V_7_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_7_out_ap_vld : OUT STD_LOGIC;
    pixbuf_y_val_V_6_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_6_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_6_out_o_ap_vld : OUT STD_LOGIC;
    pixbuf_y_val_V_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    pixbuf_y_val_V_5_out_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0_0_21075_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0_21075_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0_21075_i_out_o_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0_0516_21072_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0516_21072_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_0516_21072_i_out_o_ap_vld : OUT STD_LOGIC;
    p_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out_o_ap_vld : OUT STD_LOGIC;
    p_out1_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_out1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out1_o_ap_vld : OUT STD_LOGIC;
    p_out2_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_out2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out2_o_ap_vld : OUT STD_LOGIC;
    p_out3_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_out3_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_out3_o_ap_vld : OUT STD_LOGIC;
    p_0_1_0_0_01035_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_01035_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_01035_i_out_o_ap_vld : OUT STD_LOGIC;
    p_0_1_0_0_01031_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_01031_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_01031_i_out_o_ap_vld : OUT STD_LOGIC;
    p_0_2_0_0_01025_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_2_0_0_01025_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_2_0_0_01025_i_out_o_ap_vld : OUT STD_LOGIC;
    p_0_1_0_0_01023_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_01023_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_1_0_0_01023_i_out_o_ap_vld : OUT STD_LOGIC;
    p_0_0_0_0_05241021_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_05241021_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_0_0_0_0_05241021_i_out_o_ap_vld : OUT STD_LOGIC;
    filt_res1_1_out_i : IN STD_LOGIC_VECTOR (63 downto 0);
    filt_res1_1_out_o : OUT STD_LOGIC_VECTOR (63 downto 0);
    filt_res1_1_out_o_ap_vld : OUT STD_LOGIC );
end;


architecture behav of bd_3a92_csc_0_v_hcresampler_core_1_Pipeline_VITIS_LOOP_724_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln724_reg_799 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln732_reg_809 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op53_read_state2 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln724_reg_799_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_823 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_823_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op91_write_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal tmp_reg_823_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op128_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln724_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal stream_csc_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal stream_out_hresampled_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal conv2772_cast_cast_i_cast_cast_cast_cast_fu_250_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal conv2772_cast_cast_i_cast_cast_cast_cast_reg_794 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln724_reg_799_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal odd_col_fu_313_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal odd_col_reg_803 : STD_LOGIC_VECTOR (0 downto 0);
    signal odd_col_reg_803_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal odd_col_reg_803_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal odd_col_reg_803_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln732_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp148_i_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp148_i_reg_813 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp148_i_reg_813_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_823_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal pixbuf_y_val_V_11_reg_827 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_val_V_12_reg_834 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_val_V_13_reg_840 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_V_fu_459_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_V_reg_846 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_fu_466_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_V_reg_851 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_fu_473_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_reg_856 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_fu_480_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_reg_861 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1541_fu_491_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1541_reg_866 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1541_3_fu_501_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln1541_3_reg_871 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_i_fu_593_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_i_reg_876 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1_reg_881 : STD_LOGIC_VECTOR (7 downto 0);
    signal filt_res1_3_reg_886 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal rhs_V_2_fu_445_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal rhs_3_fu_452_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln145_fu_342_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal filt_res1_fu_693_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal x_fu_138 : STD_LOGIC_VECTOR (11 downto 0);
    signal x_4_fu_301_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_3 : STD_LOGIC_VECTOR (11 downto 0);
    signal pixbuf_y_val_V_5_fu_142 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_val_V_10_fu_146 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_val_V_7_fu_150 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_val_V_8_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_val_V_9_fu_158 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_fu_519_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln174_fu_717_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln724_fu_291_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln685_cast_fu_246_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal out_x_fu_307_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln720_cast_fu_242_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1541_2_fu_487_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1541_6_fu_497_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ret_V_fu_603_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1541_3_fu_617_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_fu_610_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1541_2_fu_620_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_1_fu_613_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1541_1_fu_626_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ret_V_2_fu_642_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1541_7_fu_656_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_4_fu_649_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1541_5_fu_659_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln1541_5_fu_652_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln1541_4_fu_665_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln587_fu_690_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln724_fu_700_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln851_fu_704_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_i_fu_710_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_595 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component bd_3a92_csc_0_mux_432_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component bd_3a92_csc_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_432_8_1_1_U211 : component bd_3a92_csc_0_mux_432_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 32,
        dout_WIDTH => 8)
    port map (
        din0 => pixbuf_y_val_V_6_out_i,
        din1 => pixbuf_y_val_V_11_reg_827,
        din2 => pixbuf_y_val_V_12_reg_834,
        din3 => pixbuf_y_val_V_13_reg_840,
        din4 => conv2772_cast_cast_i_cast_cast_cast_cast_reg_794,
        dout => tmp_2_i_fu_593_p6);

    flow_control_loop_pipe_sequential_init_U : component bd_3a92_csc_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    pixbuf_y_val_V_10_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    pixbuf_y_val_V_10_fu_146 <= p_0_0_0_0_05241026_lcssa1052_i;
                elsif ((ap_const_boolean_1 = ap_condition_595)) then 
                    pixbuf_y_val_V_10_fu_146 <= trunc_ln145_fu_342_p1;
                end if;
            end if; 
        end if;
    end process;

    pixbuf_y_val_V_5_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    pixbuf_y_val_V_5_fu_142 <= pixbuf_y_val_V;
                elsif (((icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    pixbuf_y_val_V_5_fu_142 <= pixbuf_y_val_V_10_fu_146;
                end if;
            end if; 
        end if;
    end process;

    pixbuf_y_val_V_7_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    pixbuf_y_val_V_7_fu_150 <= pixbuf_y_val_V_2;
                elsif (((icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    pixbuf_y_val_V_7_fu_150 <= pixbuf_y_val_V_8_fu_154;
                end if;
            end if; 
        end if;
    end process;

    pixbuf_y_val_V_8_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    pixbuf_y_val_V_8_fu_154 <= pixbuf_y_val_V_3;
                elsif (((icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    pixbuf_y_val_V_8_fu_154 <= pixbuf_y_val_V_9_fu_158;
                end if;
            end if; 
        end if;
    end process;

    pixbuf_y_val_V_9_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    pixbuf_y_val_V_9_fu_158 <= pixbuf_y_val_V_4;
                elsif (((icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                    pixbuf_y_val_V_9_fu_158 <= pixbuf_y_val_V_5_fu_142;
                end if;
            end if; 
        end if;
    end process;

    x_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln724_fu_295_p2 = ap_const_lv1_0))) then 
                    x_fu_138 <= x_4_fu_301_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_138 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (odd_col_reg_803_pp0_iter1_reg = ap_const_lv1_0))) then
                add_ln1541_3_reg_871 <= add_ln1541_3_fu_501_p2;
                add_ln1541_reg_866 <= add_ln1541_fu_491_p2;
                lhs_V_reg_846 <= lhs_V_fu_459_p3;
                lhs_reg_856 <= lhs_fu_473_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                cmp148_i_reg_813_pp0_iter1_reg <= cmp148_i_reg_813;
                    conv2772_cast_cast_i_cast_cast_cast_cast_reg_794(1 downto 0) <= conv2772_cast_cast_i_cast_cast_cast_cast_fu_250_p3(1 downto 0);
                icmp_ln724_reg_799 <= icmp_ln724_fu_295_p2;
                icmp_ln724_reg_799_pp0_iter1_reg <= icmp_ln724_reg_799;
                odd_col_reg_803_pp0_iter1_reg <= odd_col_reg_803;
                tmp_reg_823_pp0_iter1_reg <= tmp_reg_823;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln724_reg_799_pp0_iter2_reg <= icmp_ln724_reg_799_pp0_iter1_reg;
                odd_col_reg_803_pp0_iter2_reg <= odd_col_reg_803_pp0_iter1_reg;
                odd_col_reg_803_pp0_iter3_reg <= odd_col_reg_803_pp0_iter2_reg;
                tmp_2_i_reg_876 <= tmp_2_i_fu_593_p6;
                tmp_reg_823_pp0_iter2_reg <= tmp_reg_823_pp0_iter1_reg;
                tmp_reg_823_pp0_iter3_reg <= tmp_reg_823_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln724_fu_295_p2 = ap_const_lv1_0))) then
                cmp148_i_reg_813 <= cmp148_i_fu_323_p2;
                icmp_ln732_reg_809 <= icmp_ln732_fu_317_p2;
                odd_col_reg_803 <= odd_col_fu_313_p1;
                tmp_reg_823 <= out_x_fu_307_p2(12 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (odd_col_reg_803_pp0_iter2_reg = ap_const_lv1_0))) then
                filt_res1_3_reg_886 <= add_ln1541_4_fu_665_p2(9 downto 2);
                trunc_ln1_reg_881 <= add_ln1541_1_fu_626_p2(9 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                pixbuf_y_val_V_11_reg_827 <= pixbuf_y_val_V_7_fu_150;
                pixbuf_y_val_V_12_reg_834 <= pixbuf_y_val_V_8_fu_154;
                pixbuf_y_val_V_13_reg_840 <= pixbuf_y_val_V_9_fu_158;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0))) then
                rhs_V_reg_851 <= rhs_V_fu_466_p3;
                rhs_reg_861 <= rhs_fu_480_p3;
            end if;
        end if;
    end process;
    conv2772_cast_cast_i_cast_cast_cast_cast_reg_794(31 downto 2) <= "000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1541_1_fu_626_p2 <= std_logic_vector(unsigned(add_ln1541_2_fu_620_p2) + unsigned(zext_ln1541_1_fu_613_p1));
    add_ln1541_2_fu_620_p2 <= std_logic_vector(unsigned(zext_ln1541_3_fu_617_p1) + unsigned(zext_ln1541_fu_610_p1));
    add_ln1541_3_fu_501_p2 <= std_logic_vector(unsigned(zext_ln1541_6_fu_497_p1) + unsigned(ap_const_lv9_2));
    add_ln1541_4_fu_665_p2 <= std_logic_vector(unsigned(add_ln1541_5_fu_659_p2) + unsigned(zext_ln1541_5_fu_652_p1));
    add_ln1541_5_fu_659_p2 <= std_logic_vector(unsigned(zext_ln1541_7_fu_656_p1) + unsigned(zext_ln1541_4_fu_649_p1));
    add_ln1541_fu_491_p2 <= std_logic_vector(unsigned(zext_ln1541_2_fu_487_p1) + unsigned(ap_const_lv9_2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, stream_csc_empty_n, ap_predicate_op53_read_state2, stream_out_hresampled_full_n, ap_predicate_op91_write_state3, ap_predicate_op128_write_state5)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_predicate_op128_write_state5 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_predicate_op91_write_state3 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op53_read_state2 = ap_const_boolean_1) and (stream_csc_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, stream_csc_empty_n, ap_predicate_op53_read_state2, stream_out_hresampled_full_n, ap_predicate_op91_write_state3, ap_predicate_op128_write_state5)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_predicate_op128_write_state5 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_predicate_op91_write_state3 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op53_read_state2 = ap_const_boolean_1) and (stream_csc_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, stream_csc_empty_n, ap_predicate_op53_read_state2, stream_out_hresampled_full_n, ap_predicate_op91_write_state3, ap_predicate_op128_write_state5)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_predicate_op128_write_state5 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_predicate_op91_write_state3 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_predicate_op53_read_state2 = ap_const_boolean_1) and (stream_csc_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(stream_csc_empty_n, ap_predicate_op53_read_state2)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((ap_predicate_op53_read_state2 = ap_const_boolean_1) and (stream_csc_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(stream_out_hresampled_full_n, ap_predicate_op91_write_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op91_write_state3 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter4_assign_proc : process(stream_out_hresampled_full_n, ap_predicate_op128_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((ap_predicate_op128_write_state5 = ap_const_boolean_1) and (stream_out_hresampled_full_n = ap_const_logic_0));
    end process;


    ap_condition_595_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809)
    begin
                ap_condition_595 <= ((icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln724_fu_295_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln724_fu_295_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op128_write_state5_assign_proc : process(tmp_reg_823_pp0_iter3_reg, p_read)
    begin
                ap_predicate_op128_write_state5 <= ((tmp_reg_823_pp0_iter3_reg = ap_const_lv1_0) and (p_read = ap_const_lv1_0));
    end process;


    ap_predicate_op53_read_state2_assign_proc : process(icmp_ln724_reg_799, icmp_ln732_reg_809)
    begin
                ap_predicate_op53_read_state2 <= ((icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0));
    end process;


    ap_predicate_op91_write_state3_assign_proc : process(icmp_ln724_reg_799_pp0_iter1_reg, tmp_reg_823_pp0_iter1_reg, p_read)
    begin
                ap_predicate_op91_write_state3 <= ((p_read = ap_const_lv1_1) and (tmp_reg_823_pp0_iter1_reg = ap_const_lv1_0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_138, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_3 <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_x_3 <= x_fu_138;
        end if; 
    end process;

    cmp148_i_fu_323_p2 <= "1" when (ap_sig_allocacmp_x_3 = ap_const_lv12_0) else "0";
    conv2772_cast_cast_i_cast_cast_cast_cast_fu_250_p3 <= 
        ap_const_lv32_3 when (conv2772_cast_cast_i_cast_cast(0) = '1') else 
        ap_const_lv32_0;

    filt_res1_1_out_o_assign_proc : process(ap_enable_reg_pp0_iter4, filt_res1_1_out_i, ap_block_pp0_stage0, filt_res1_fu_693_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            filt_res1_1_out_o <= filt_res1_fu_693_p3;
        else 
            filt_res1_1_out_o <= filt_res1_1_out_i;
        end if; 
    end process;


    filt_res1_1_out_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            filt_res1_1_out_o_ap_vld <= ap_const_logic_1;
        else 
            filt_res1_1_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    filt_res1_fu_693_p3 <= 
        filt_res1_1_out_i when (odd_col_reg_803_pp0_iter3_reg(0) = '1') else 
        zext_ln587_fu_690_p1;
    icmp_ln724_fu_295_p2 <= "1" when (ap_sig_allocacmp_x_3 = loopWidth) else "0";
    icmp_ln732_fu_317_p2 <= "1" when (unsigned(ap_sig_allocacmp_x_3) < unsigned(zext_ln720_cast_fu_242_p1)) else "0";
    lhs_V_fu_459_p3 <= 
        p_0_1_0_0_01035_i_out_i when (cmp148_i_reg_813_pp0_iter1_reg(0) = '1') else 
        p_out2_i;
    lhs_fu_473_p3 <= 
        p_0_1_0_0_01031_i_out_i when (cmp148_i_reg_813_pp0_iter1_reg(0) = '1') else 
        p_out3_i;
    odd_col_fu_313_p1 <= out_x_fu_307_p2(1 - 1 downto 0);
    out_x_fu_307_p2 <= std_logic_vector(unsigned(zext_ln724_fu_291_p1) - unsigned(select_ln685_cast_fu_246_p1));

    p_0_0_0_0_0516_21072_i_out_o_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, p_0_0_0_0_0516_21072_i_out_i, p_0_1_0_0_01031_i_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_0_0_0_0_0516_21072_i_out_o <= p_0_1_0_0_01031_i_out_i;
        else 
            p_0_0_0_0_0516_21072_i_out_o <= p_0_0_0_0_0516_21072_i_out_i;
        end if; 
    end process;


    p_0_0_0_0_0516_21072_i_out_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_0_0_0_0_0516_21072_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0_0516_21072_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_0_0_0_05241021_i_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809, p_0_0_0_0_05241021_i_out_i, ap_block_pp0_stage0, trunc_ln145_fu_342_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_0_0_05241021_i_out_o <= trunc_ln145_fu_342_p1;
        else 
            p_0_0_0_0_05241021_i_out_o <= p_0_0_0_0_05241021_i_out_i;
        end if; 
    end process;


    p_0_0_0_0_05241021_i_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_0_0_0_05241021_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0_05241021_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_0_0_0_0_21075_i_out_o_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, p_0_0_0_0_0_21075_i_out_i, p_0_1_0_0_01035_i_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_0_0_0_0_0_21075_i_out_o <= p_0_1_0_0_01035_i_out_i;
        else 
            p_0_0_0_0_0_21075_i_out_o <= p_0_0_0_0_0_21075_i_out_i;
        end if; 
    end process;


    p_0_0_0_0_0_21075_i_out_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_0_0_0_0_0_21075_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_0_0_0_0_21075_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_1_0_0_01023_i_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_csc_dout, icmp_ln724_reg_799, icmp_ln732_reg_809, p_0_1_0_0_01023_i_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_01023_i_out_o <= stream_csc_dout(15 downto 8);
        else 
            p_0_1_0_0_01023_i_out_o <= p_0_1_0_0_01023_i_out_i;
        end if; 
    end process;


    p_0_1_0_0_01023_i_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_01023_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_1_0_0_01023_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_1_0_0_01031_i_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_csc_dout, icmp_ln724_reg_799, icmp_ln732_reg_809, p_0_1_0_0_01031_i_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_01031_i_out_o <= stream_csc_dout(15 downto 8);
        else 
            p_0_1_0_0_01031_i_out_o <= p_0_1_0_0_01031_i_out_i;
        end if; 
    end process;


    p_0_1_0_0_01031_i_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_01031_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_1_0_0_01031_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_1_0_0_01035_i_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_csc_dout, icmp_ln724_reg_799, icmp_ln732_reg_809, p_0_1_0_0_01035_i_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_01035_i_out_o <= stream_csc_dout(23 downto 16);
        else 
            p_0_1_0_0_01035_i_out_o <= p_0_1_0_0_01035_i_out_i;
        end if; 
    end process;


    p_0_1_0_0_01035_i_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_1_0_0_01035_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_1_0_0_01035_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_0_2_0_0_01025_i_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_csc_dout, icmp_ln724_reg_799, icmp_ln732_reg_809, p_0_2_0_0_01025_i_out_i, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_2_0_0_01025_i_out_o <= stream_csc_dout(23 downto 16);
        else 
            p_0_2_0_0_01025_i_out_o <= p_0_2_0_0_01025_i_out_i;
        end if; 
    end process;


    p_0_2_0_0_01025_i_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln724_reg_799, icmp_ln732_reg_809, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln732_reg_809 = ap_const_lv1_1) and (icmp_ln724_reg_799 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_0_2_0_0_01025_i_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_0_2_0_0_01025_i_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_0_fu_519_p4 <= ((p_0_2_0_0_01025_i_out_i & p_0_1_0_0_01023_i_out_i) & p_0_0_0_0_05241021_i_out_i);

    p_out1_o_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, p_out1_i, ap_block_pp0_stage0, rhs_3_fu_452_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out1_o <= rhs_3_fu_452_p3;
        else 
            p_out1_o <= p_out1_i;
        end if; 
    end process;


    p_out1_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out1_o_ap_vld <= ap_const_logic_1;
        else 
            p_out1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out2_o_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, p_out2_i, ap_block_pp0_stage0, rhs_V_fu_466_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out2_o <= rhs_V_fu_466_p3;
        else 
            p_out2_o <= p_out2_i;
        end if; 
    end process;


    p_out2_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out2_o_ap_vld <= ap_const_logic_1;
        else 
            p_out2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out3_o_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, p_out3_i, ap_block_pp0_stage0, rhs_fu_480_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out3_o <= rhs_fu_480_p3;
        else 
            p_out3_o <= p_out3_i;
        end if; 
    end process;


    p_out3_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out3_o_ap_vld <= ap_const_logic_1;
        else 
            p_out3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_o_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, p_out_i, ap_block_pp0_stage0, rhs_V_2_fu_445_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out_o <= rhs_V_2_fu_445_p3;
        else 
            p_out_o <= p_out_i;
        end if; 
    end process;


    p_out_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln724_reg_799_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_out_o_ap_vld <= ap_const_logic_1;
        else 
            p_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pixbuf_y_val_V_5_out <= pixbuf_y_val_V_5_fu_142;

    pixbuf_y_val_V_5_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln724_reg_799_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter2_reg = ap_const_lv1_1))) then 
            pixbuf_y_val_V_5_out_ap_vld <= ap_const_logic_1;
        else 
            pixbuf_y_val_V_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    pixbuf_y_val_V_6_out_o_assign_proc : process(ap_enable_reg_pp0_iter3, pixbuf_y_val_V_6_out_i, ap_block_pp0_stage0, pixbuf_y_val_V_11_reg_827)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            pixbuf_y_val_V_6_out_o <= pixbuf_y_val_V_11_reg_827;
        else 
            pixbuf_y_val_V_6_out_o <= pixbuf_y_val_V_6_out_i;
        end if; 
    end process;


    pixbuf_y_val_V_6_out_o_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            pixbuf_y_val_V_6_out_o_ap_vld <= ap_const_logic_1;
        else 
            pixbuf_y_val_V_6_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pixbuf_y_val_V_7_out <= pixbuf_y_val_V_11_reg_827;

    pixbuf_y_val_V_7_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln724_reg_799_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter2_reg = ap_const_lv1_1))) then 
            pixbuf_y_val_V_7_out_ap_vld <= ap_const_logic_1;
        else 
            pixbuf_y_val_V_7_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pixbuf_y_val_V_8_out <= pixbuf_y_val_V_12_reg_834;

    pixbuf_y_val_V_8_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln724_reg_799_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter2_reg = ap_const_lv1_1))) then 
            pixbuf_y_val_V_8_out_ap_vld <= ap_const_logic_1;
        else 
            pixbuf_y_val_V_8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pixbuf_y_val_V_9_out <= pixbuf_y_val_V_13_reg_840;

    pixbuf_y_val_V_9_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln724_reg_799_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln724_reg_799_pp0_iter2_reg = ap_const_lv1_1))) then 
            pixbuf_y_val_V_9_out_ap_vld <= ap_const_logic_1;
        else 
            pixbuf_y_val_V_9_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_2_fu_642_p3 <= (rhs_V_reg_851 & ap_const_lv1_0);
    ret_V_fu_603_p3 <= (rhs_reg_861 & ap_const_lv1_0);
    rhs_3_fu_452_p3 <= 
        p_0_1_0_0_01031_i_out_i when (cmp148_i_reg_813_pp0_iter1_reg(0) = '1') else 
        p_0_0_0_0_0516_21072_i_out_i;
    rhs_V_2_fu_445_p3 <= 
        p_0_1_0_0_01035_i_out_i when (cmp148_i_reg_813_pp0_iter1_reg(0) = '1') else 
        p_0_0_0_0_0_21075_i_out_i;
    rhs_V_fu_466_p3 <= 
        p_0_1_0_0_01035_i_out_i when (cmp148_i_reg_813_pp0_iter1_reg(0) = '1') else 
        p_out_i;
    rhs_fu_480_p3 <= 
        p_0_1_0_0_01031_i_out_i when (cmp148_i_reg_813_pp0_iter1_reg(0) = '1') else 
        p_out1_i;
    select_ln685_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln685),13));
    select_ln851_fu_704_p3 <= 
        trunc_ln724_fu_700_p1 when (odd_col_reg_803_pp0_iter3_reg(0) = '1') else 
        trunc_ln1_reg_881;

    stream_csc_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, stream_csc_empty_n, ap_predicate_op53_read_state2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op53_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_blk_n <= stream_csc_empty_n;
        else 
            stream_csc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_csc_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_predicate_op53_read_state2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op53_read_state2 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_read <= ap_const_logic_1;
        else 
            stream_csc_read <= ap_const_logic_0;
        end if; 
    end process;


    stream_out_hresampled_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, stream_out_hresampled_full_n, ap_predicate_op91_write_state3, ap_predicate_op128_write_state5, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op128_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op91_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            stream_out_hresampled_blk_n <= stream_out_hresampled_full_n;
        else 
            stream_out_hresampled_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_out_hresampled_din_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_predicate_op91_write_state3, ap_predicate_op128_write_state5, p_0_fu_519_p4, ap_block_pp0_stage0_01001, zext_ln174_fu_717_p1)
    begin
        if ((ap_const_boolean_0 = ap_block_pp0_stage0_01001)) then
            if (((ap_predicate_op128_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
                stream_out_hresampled_din <= zext_ln174_fu_717_p1;
            elsif (((ap_predicate_op91_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
                stream_out_hresampled_din <= p_0_fu_519_p4;
            else 
                stream_out_hresampled_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            stream_out_hresampled_din <= "XXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    stream_out_hresampled_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_predicate_op91_write_state3, ap_predicate_op128_write_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op128_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op91_write_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            stream_out_hresampled_write <= ap_const_logic_1;
        else 
            stream_out_hresampled_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_i_fu_710_p3 <= (select_ln851_fu_704_p3 & tmp_2_i_reg_876);
    trunc_ln145_fu_342_p1 <= stream_csc_dout(8 - 1 downto 0);
    trunc_ln724_fu_700_p1 <= filt_res1_1_out_i(8 - 1 downto 0);
    x_4_fu_301_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_3) + unsigned(ap_const_lv12_1));
    zext_ln1541_1_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_fu_603_p3),10));
    zext_ln1541_2_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_3_fu_452_p3),9));
    zext_ln1541_3_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1541_reg_866),10));
    zext_ln1541_4_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_V_reg_846),10));
    zext_ln1541_5_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_2_fu_642_p3),10));
    zext_ln1541_6_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_V_2_fu_445_p3),9));
    zext_ln1541_7_fu_656_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1541_3_reg_871),10));
    zext_ln1541_fu_610_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lhs_reg_856),10));
    zext_ln174_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_i_fu_710_p3),24));
    zext_ln587_fu_690_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(filt_res1_3_reg_886),64));
    zext_ln720_cast_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln720),12));
    zext_ln724_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_3),13));
end behav;
