// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_3a92_csc_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_619_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_out_hresampled_dout,
        stream_out_hresampled_num_data_valid,
        stream_out_hresampled_fifo_cap,
        stream_out_hresampled_empty_n,
        stream_out_hresampled_read,
        m_axis_video_TREADY,
        sof,
        cols,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        p_read,
        sub
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_out_hresampled_dout;
input  [4:0] stream_out_hresampled_num_data_valid;
input  [4:0] stream_out_hresampled_fifo_cap;
input   stream_out_hresampled_empty_n;
output   stream_out_hresampled_read;
input   m_axis_video_TREADY;
input  [0:0] sof;
input  [10:0] cols;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [7:0] p_read;
input  [10:0] sub;

reg ap_idle;
reg stream_out_hresampled_read;
reg m_axis_video_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln619_reg_376;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln619_reg_376_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln619_fu_213_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    m_axis_video_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_out_hresampled_blk_n;
reg   [0:0] tmp_user_V_reg_159;
wire   [7:0] p_read_55_reg_367;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_last_V_fu_225_p2;
reg   [0:0] tmp_last_V_reg_380;
reg   [0:0] tmp_last_V_reg_380_pp0_iter1_reg;
wire   [7:0] pix_rgb_V_fu_236_p1;
reg   [7:0] pix_rgb_V_reg_385;
wire   [7:0] pix_444_V_1_fu_240_p4;
reg   [7:0] pix_444_V_1_reg_390;
reg   [7:0] pix_444_V_reg_396;
wire   [8:0] p_Result_4_fu_260_p3;
wire   [8:0] p_Result_3_fu_268_p3;
wire   [8:0] p_Result_5_fu_276_p3;
wire    ap_loop_init;
wire   [8:0] ap_phi_reg_pp0_iter0_p_Val2_s_reg_171;
reg   [8:0] ap_phi_reg_pp0_iter1_p_Val2_s_reg_171;
reg   [8:0] ap_phi_reg_pp0_iter2_p_Val2_s_reg_171;
reg   [23:0] ap_phi_mux_p_Val2_1_phi_fu_185_p6;
wire   [23:0] p_Result_7_fu_312_p5;
wire   [23:0] ap_phi_reg_pp0_iter2_p_Val2_1_reg_182;
wire   [23:0] p_Result_2_fu_288_p5;
wire   [23:0] p_Result_6_fu_300_p5;
reg   [23:0] ap_phi_mux_axi_data_V_12_phi_fu_196_p6;
wire   [23:0] p_Result_9_fu_348_p5;
wire   [23:0] ap_phi_reg_pp0_iter2_axi_data_V_12_reg_193;
wire   [23:0] p_Result_s_fu_324_p5;
wire   [23:0] p_Result_8_fu_336_p5;
reg   [10:0] j_fu_96;
wire   [10:0] j_2_fu_219_p2;
reg   [10:0] ap_sig_allocacmp_j_1;
reg    ap_block_pp0_stage0_01001;
wire  signed [23:0] sext_ln573_fu_284_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_144;
reg    ap_condition_159;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

bd_3a92_csc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_159)) begin
        if (((icmp_ln619_reg_376 == 1'd0) & (p_read_55_reg_367 == 8'd0))) begin
            ap_phi_reg_pp0_iter2_p_Val2_s_reg_171 <= p_Result_3_fu_268_p3;
        end else if (((icmp_ln619_reg_376 == 1'd0) & (p_read_55_reg_367 == 8'd1))) begin
            ap_phi_reg_pp0_iter2_p_Val2_s_reg_171 <= p_Result_4_fu_260_p3;
        end else if ((1'b1 == ap_condition_144)) begin
            ap_phi_reg_pp0_iter2_p_Val2_s_reg_171 <= p_Result_5_fu_276_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_Val2_s_reg_171 <= ap_phi_reg_pp0_iter1_p_Val2_s_reg_171;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln619_fu_213_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_96 <= j_2_fu_219_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_96 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        tmp_user_V_reg_159 <= sof;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tmp_user_V_reg_159 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln619_reg_376 <= icmp_ln619_fu_213_p2;
        icmp_ln619_reg_376_pp0_iter1_reg <= icmp_ln619_reg_376;
        tmp_last_V_reg_380_pp0_iter1_reg <= tmp_last_V_reg_380;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_p_Val2_s_reg_171 <= ap_phi_reg_pp0_iter0_p_Val2_s_reg_171;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln619_reg_376 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pix_444_V_1_reg_390 <= {{stream_out_hresampled_dout[15:8]}};
        pix_444_V_reg_396 <= {{stream_out_hresampled_dout[23:16]}};
        pix_rgb_V_reg_385 <= pix_rgb_V_fu_236_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln619_fu_213_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_last_V_reg_380 <= tmp_last_V_fu_225_p2;
    end
end

always @ (*) begin
    if (((icmp_ln619_fu_213_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0)) begin
        if ((p_read_55_reg_367 == 8'd0)) begin
            ap_phi_mux_axi_data_V_12_phi_fu_196_p6 = p_Result_8_fu_336_p5;
        end else if ((p_read_55_reg_367 == 8'd1)) begin
            ap_phi_mux_axi_data_V_12_phi_fu_196_p6 = p_Result_s_fu_324_p5;
        end else if ((~(p_read_55_reg_367 == 8'd0) & ~(p_read_55_reg_367 == 8'd1))) begin
            ap_phi_mux_axi_data_V_12_phi_fu_196_p6 = p_Result_9_fu_348_p5;
        end else begin
            ap_phi_mux_axi_data_V_12_phi_fu_196_p6 = ap_phi_reg_pp0_iter2_axi_data_V_12_reg_193;
        end
    end else begin
        ap_phi_mux_axi_data_V_12_phi_fu_196_p6 = ap_phi_reg_pp0_iter2_axi_data_V_12_reg_193;
    end
end

always @ (*) begin
    if ((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0)) begin
        if ((p_read_55_reg_367 == 8'd0)) begin
            ap_phi_mux_p_Val2_1_phi_fu_185_p6 = p_Result_6_fu_300_p5;
        end else if ((p_read_55_reg_367 == 8'd1)) begin
            ap_phi_mux_p_Val2_1_phi_fu_185_p6 = p_Result_2_fu_288_p5;
        end else if ((~(p_read_55_reg_367 == 8'd0) & ~(p_read_55_reg_367 == 8'd1))) begin
            ap_phi_mux_p_Val2_1_phi_fu_185_p6 = p_Result_7_fu_312_p5;
        end else begin
            ap_phi_mux_p_Val2_1_phi_fu_185_p6 = ap_phi_reg_pp0_iter2_p_Val2_1_reg_182;
        end
    end else begin
        ap_phi_mux_p_Val2_1_phi_fu_185_p6 = ap_phi_reg_pp0_iter2_p_Val2_1_reg_182;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_1 = j_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        m_axis_video_TVALID = 1'b1;
    end else begin
        m_axis_video_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln619_reg_376 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_out_hresampled_blk_n = stream_out_hresampled_empty_n;
    end else begin
        stream_out_hresampled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln619_reg_376 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_out_hresampled_read = 1'b1;
    end else begin
        stream_out_hresampled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((icmp_ln619_reg_376 == 1'd0) & (stream_out_hresampled_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY == 1'b0)))) | ((icmp_ln619_reg_376 == 1'd0) & (stream_out_hresampled_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY == 1'b0)))) | ((icmp_ln619_reg_376 == 1'd0) & (stream_out_hresampled_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln619_reg_376 == 1'd0) & (stream_out_hresampled_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln619_reg_376_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_144 = (~(p_read_55_reg_367 == 8'd0) & ~(p_read_55_reg_367 == 8'd1) & (icmp_ln619_reg_376 == 1'd0));
end

always @ (*) begin
    ap_condition_159 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_p_Val2_s_reg_171 = 'bx;

assign ap_phi_reg_pp0_iter2_axi_data_V_12_reg_193 = 'bx;

assign ap_phi_reg_pp0_iter2_p_Val2_1_reg_182 = 'bx;

assign icmp_ln619_fu_213_p2 = ((ap_sig_allocacmp_j_1 == cols) ? 1'b1 : 1'b0);

assign j_2_fu_219_p2 = (ap_sig_allocacmp_j_1 + 11'd1);

assign m_axis_video_TDATA = ap_phi_mux_axi_data_V_12_phi_fu_196_p6;

assign m_axis_video_TDEST = 1'd0;

assign m_axis_video_TID = 1'd0;

assign m_axis_video_TKEEP = 3'd7;

assign m_axis_video_TLAST = tmp_last_V_reg_380_pp0_iter1_reg;

assign m_axis_video_TSTRB = 3'd0;

assign m_axis_video_TUSER = tmp_user_V_reg_159;

assign p_Result_2_fu_288_p5 = {{sext_ln573_fu_284_p1[23:16]}, {pix_444_V_1_reg_390}, {sext_ln573_fu_284_p1[7:0]}};

assign p_Result_3_fu_268_p3 = {{1'd1}, {pix_444_V_1_fu_240_p4}};

assign p_Result_4_fu_260_p3 = {{1'd1}, {pix_rgb_V_fu_236_p1}};

assign p_Result_5_fu_276_p3 = {{1'd1}, {pix_rgb_V_fu_236_p1}};

assign p_Result_6_fu_300_p5 = {{sext_ln573_fu_284_p1[23:16]}, {pix_444_V_reg_396}, {sext_ln573_fu_284_p1[7:0]}};

assign p_Result_7_fu_312_p5 = {{sext_ln573_fu_284_p1[23:16]}, {pix_444_V_1_reg_390}, {sext_ln573_fu_284_p1[7:0]}};

assign p_Result_8_fu_336_p5 = {{pix_rgb_V_reg_385}, {ap_phi_mux_p_Val2_1_phi_fu_185_p6[15:0]}};

assign p_Result_9_fu_348_p5 = {{pix_444_V_reg_396}, {ap_phi_mux_p_Val2_1_phi_fu_185_p6[15:0]}};

assign p_Result_s_fu_324_p5 = {{pix_444_V_reg_396}, {ap_phi_mux_p_Val2_1_phi_fu_185_p6[15:0]}};

assign p_read_55_reg_367 = p_read;

assign pix_444_V_1_fu_240_p4 = {{stream_out_hresampled_dout[15:8]}};

assign pix_rgb_V_fu_236_p1 = stream_out_hresampled_dout[7:0];

assign sext_ln573_fu_284_p1 = $signed(ap_phi_reg_pp0_iter2_p_Val2_s_reg_171);

assign tmp_last_V_fu_225_p2 = ((ap_sig_allocacmp_j_1 == sub) ? 1'b1 : 1'b0);

endmodule //bd_3a92_csc_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_619_2
