// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_3a92_ltr_0_AXIvideo2MultiPixStream (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        srcYUV_din,
        srcYUV_num_data_valid,
        srcYUV_fifo_cap,
        srcYUV_full_n,
        srcYUV_write,
        height,
        width,
        video_format
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [23:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [2:0] s_axis_video_TKEEP;
input  [2:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [23:0] srcYUV_din;
input  [4:0] srcYUV_num_data_valid;
input  [4:0] srcYUV_fifo_cap;
input   srcYUV_full_n;
output   srcYUV_write;
input  [15:0] height;
input  [15:0] width;
input  [15:0] video_format;

reg ap_done;
reg ap_idle;
reg start_write;
reg srcYUV_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [10:0] grp_reg_unsigned_short_s_fu_257_ap_return;
reg   [10:0] rows_reg_377;
wire    ap_CS_fsm_state4;
wire   [10:0] grp_reg_unsigned_short_s_fu_262_ap_return;
reg   [10:0] cols_reg_382;
wire   [0:0] cmp8460_fu_270_p2;
reg   [0:0] cmp8460_reg_390;
wire   [0:0] icmp_ln265_fu_285_p2;
reg   [0:0] icmp_ln265_reg_399;
wire    ap_CS_fsm_state5;
wire   [10:0] i_4_fu_290_p2;
reg   [10:0] i_4_reg_403;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_s_axis_video_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_data_V_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_data_V_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_last_V_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_last_V_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_ready;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_srcYUV_din;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_srcYUV_write;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_cond;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_eol_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_eol_out_ap_vld;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_axi_data_V_15_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_axi_data_V_15_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_done;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_idle;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_ready;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_s_axis_video_TREADY;
wire   [23:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_data_V_16_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_data_V_16_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_last_V_4_out;
wire    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_last_V_4_out_ap_vld;
wire   [10:0] grp_reg_unsigned_short_s_fu_257_d;
wire   [10:0] grp_reg_unsigned_short_s_fu_262_d;
reg   [0:0] axi_last_V_2_reg_122;
wire    ap_CS_fsm_state11;
reg   [23:0] axi_data_2_lcssa_reg_132;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state6;
reg   [0:0] axi_last_2_lcssa_reg_142;
reg   [0:0] eol_0_lcssa_reg_153;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [23:0] axi_data_V_14_fu_80;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [0:0] axi_last_V_4_loc_fu_88;
reg   [10:0] i_fu_76;
reg    ap_block_state1;
reg   [0:0] sof_fu_84;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [23:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [2:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [2:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start_reg = 1'b0;
end

bd_3a92_ltr_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_V_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_data_V_out),
    .axi_data_V_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_data_V_out_ap_vld),
    .axi_last_V_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_last_V_out),
    .axi_last_V_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_last_V_out_ap_vld)
);

bd_3a92_ltr_0_AXIvideo2MultiPixStream_Pipeline_loop_width grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .srcYUV_din(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_srcYUV_din),
    .srcYUV_num_data_valid(5'd0),
    .srcYUV_fifo_cap(5'd0),
    .srcYUV_full_n(srcYUV_full_n),
    .srcYUV_write(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_srcYUV_write),
    .sof_5(sof_fu_84),
    .axi_last_V_2(axi_last_V_2_reg_122),
    .axi_data_V_14(axi_data_V_14_fu_80),
    .cols(cols_reg_382),
    .cond(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_cond),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .eol_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_eol_out_ap_vld),
    .axi_data_V_15_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_axi_data_V_15_out),
    .axi_data_V_15_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_axi_data_V_15_out_ap_vld)
);

bd_3a92_ltr_0_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .axi_data_2_lcssa(axi_data_2_lcssa_reg_132),
    .axi_last_2_lcssa(axi_last_2_lcssa_reg_142),
    .eol_0_lcssa(eol_0_lcssa_reg_153),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_V_16_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_data_V_16_out),
    .axi_data_V_16_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_data_V_16_out_ap_vld),
    .axi_last_V_4_out(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_last_V_4_out),
    .axi_last_V_4_out_ap_vld(grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_last_V_4_out_ap_vld)
);

bd_3a92_ltr_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_257(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_unsigned_short_s_fu_257_d),
    .ap_return(grp_reg_unsigned_short_s_fu_257_ap_return)
);

bd_3a92_ltr_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_262(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_unsigned_short_s_fu_262_d),
    .ap_return(grp_reg_unsigned_short_s_fu_262_ap_return)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

bd_3a92_ltr_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln265_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln265_reg_399 == 1'd0) & (cmp8460_reg_390 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln265_reg_399 == 1'd0) & (cmp8460_reg_390 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        axi_data_2_lcssa_reg_132 <= axi_data_V_14_fu_80;
    end else if (((cmp8460_reg_390 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        axi_data_2_lcssa_reg_132 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_axi_data_V_15_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_data_V_16_out_ap_vld == 1'b1))) begin
        axi_data_V_14_fu_80 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_data_V_16_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_data_V_out_ap_vld == 1'b1))) begin
        axi_data_V_14_fu_80 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_data_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln265_reg_399 == 1'd0) & (cmp8460_reg_390 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        axi_last_2_lcssa_reg_142 <= axi_last_V_2_reg_122;
    end else if (((cmp8460_reg_390 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        axi_last_2_lcssa_reg_142 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        axi_last_V_2_reg_122 <= axi_last_V_4_loc_fu_88;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_V_2_reg_122 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_axi_last_V_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln265_reg_399 == 1'd0) & (cmp8460_reg_390 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        eol_0_lcssa_reg_153 <= 1'd0;
    end else if (((cmp8460_reg_390 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        eol_0_lcssa_reg_153 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_76 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_fu_76 <= i_4_reg_403;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_84 <= 1'd1;
    end else if (((cmp8460_reg_390 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        sof_fu_84 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_last_V_4_out_ap_vld == 1'b1))) begin
        axi_last_V_4_loc_fu_88 <= grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_axi_last_V_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp8460_reg_390 <= cmp8460_fu_270_p2;
        cols_reg_382 <= grp_reg_unsigned_short_s_fu_262_ap_return;
        rows_reg_377 <= grp_reg_unsigned_short_s_fu_257_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_4_reg_403 <= i_4_fu_290_p2;
        icmp_ln265_reg_399 <= icmp_ln265_fu_285_p2;
    end
end

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln265_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln265_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        srcYUV_write = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_srcYUV_write;
    end else begin
        srcYUV_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln265_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln265_reg_399 == 1'd0) & (cmp8460_reg_390 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign cmp8460_fu_270_p2 = ((grp_reg_unsigned_short_s_fu_262_ap_return == 11'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_eol_fu_213_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_wait_for_start_fu_165_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_cond = ((video_format == 16'd0) ? 1'b1 : 1'b0);

assign grp_reg_unsigned_short_s_fu_257_d = height[10:0];

assign grp_reg_unsigned_short_s_fu_262_d = width[10:0];

assign i_4_fu_290_p2 = (i_fu_76 + 11'd1);

assign icmp_ln265_fu_285_p2 = ((i_fu_76 == rows_reg_377) ? 1'b1 : 1'b0);

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign srcYUV_din = grp_AXIvideo2MultiPixStream_Pipeline_loop_width_fu_185_srcYUV_din;

assign start_out = real_start;

endmodule //bd_3a92_ltr_0_AXIvideo2MultiPixStream
