// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_3a92_hsc_0_v_hcresampler_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_in_dout,
        stream_in_num_data_valid,
        stream_in_fifo_cap,
        stream_in_empty_n,
        stream_in_read,
        Height,
        WidthIn,
        p_read,
        stream_upsampled_din,
        stream_upsampled_num_data_valid,
        stream_upsampled_fifo_cap,
        stream_upsampled_full_n,
        stream_upsampled_write
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_in_dout;
input  [4:0] stream_in_num_data_valid;
input  [4:0] stream_in_fifo_cap;
input   stream_in_empty_n;
output   stream_in_read;
input  [15:0] Height;
input  [15:0] WidthIn;
input  [0:0] p_read;
output  [23:0] stream_upsampled_din;
input  [4:0] stream_upsampled_num_data_valid;
input  [4:0] stream_upsampled_fifo_cap;
input   stream_upsampled_full_n;
output   stream_upsampled_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_in_read;
reg stream_upsampled_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire   [15:0] loopWidth_fu_197_p2;
reg   [15:0] loopWidth_reg_386;
wire   [14:0] trunc_ln1597_fu_203_p1;
reg   [14:0] trunc_ln1597_reg_391;
wire    ap_CS_fsm_state3;
wire   [2:0] select_ln1632_fu_207_p3;
reg   [2:0] select_ln1632_reg_401;
wire   [0:0] cmp361000_fu_214_p2;
reg   [0:0] cmp361000_reg_406;
wire   [14:0] y_4_fu_231_p2;
reg   [14:0] y_4_reg_413;
wire    ap_CS_fsm_state4;
reg   [7:0] pixbuf_y_val_V_16_load_reg_418;
wire   [0:0] icmp_ln1634_fu_226_p2;
reg   [7:0] pixbuf_y_val_V_17_load_reg_423;
reg   [7:0] pixbuf_y_val_V_18_load_reg_428;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_done;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_idle;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_ready;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_in_read;
wire   [23:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_upsampled_din;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_upsampled_write;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_24_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_24_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_23_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_23_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_22_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_22_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_21_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_21_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_20_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_20_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0_21063_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0_21063_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0511_21060_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0511_21060_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out1_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out1_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out2_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out2_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out3_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out3_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01024_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01024_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01020_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01020_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_2_0_0_01014_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_2_0_0_01014_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01012_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01012_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_05191010_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_05191010_out_o_ap_vld;
reg    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [7:0] pixbuf_y_val_V_18_fu_126;
reg   [7:0] pixbuf_y_val_V_17_fu_122;
reg   [7:0] pixbuf_y_val_V_16_fu_118;
reg   [7:0] pixbuf_y_val_V_15_fu_114;
reg   [7:0] p_0_0_0_0_0_21061_lcssa1087_fu_106;
reg   [7:0] p_0_0_0_0_0511_21058_lcssa1084_fu_102;
reg   [7:0] p_lcssa10571081_fu_98;
reg   [7:0] p_lcssa10561078_fu_94;
reg   [7:0] p_lcssa10541072_fu_90;
reg   [7:0] p_lcssa1066_fu_86;
reg   [7:0] p_0_1_0_0_01021_lcssa1046_fu_82;
reg   [7:0] p_0_1_0_0_01017_lcssa1043_fu_78;
reg   [7:0] p_0_2_0_0_01013_lcssa1037_fu_70;
reg   [7:0] p_0_1_0_0_01011_lcssa1034_fu_66;
reg   [7:0] p_0_0_0_0_05191009_lcssa1031_fu_62;
reg   [14:0] y_fu_58;
wire    ap_CS_fsm_state7;
reg    ap_block_state1;
reg   [7:0] p_0_0_0_0_05191015_lcssa1040_fu_74;
reg   [7:0] pixbuf_y_val_V_fu_110;
wire   [15:0] select_ln1632_2_fu_190_p3;
wire   [15:0] zext_ln1634_fu_222_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start_reg = 1'b0;
end

bd_3a92_hsc_0_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2 grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start),
    .ap_done(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_done),
    .ap_idle(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_idle),
    .ap_ready(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_ready),
    .stream_in_dout(stream_in_dout),
    .stream_in_num_data_valid(5'd0),
    .stream_in_fifo_cap(5'd0),
    .stream_in_empty_n(stream_in_empty_n),
    .stream_in_read(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_in_read),
    .stream_upsampled_din(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_upsampled_din),
    .stream_upsampled_num_data_valid(5'd0),
    .stream_upsampled_fifo_cap(5'd0),
    .stream_upsampled_full_n(stream_upsampled_full_n),
    .stream_upsampled_write(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_upsampled_write),
    .pixbuf_y_val_V_19(pixbuf_y_val_V_18_load_reg_428),
    .pixbuf_y_val_V_18(pixbuf_y_val_V_17_load_reg_423),
    .pixbuf_y_val_V_17(pixbuf_y_val_V_16_load_reg_418),
    .pixbuf_y_val_V(pixbuf_y_val_V_fu_110),
    .p_0_0_0_0_05191015_lcssa1040(p_0_0_0_0_05191015_lcssa1040_fu_74),
    .loopWidth(trunc_ln1597_reg_391),
    .select_ln1632(select_ln1632_reg_401),
    .WidthIn_load(WidthIn),
    .p_read(p_read),
    .pixbuf_y_val_V_24_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_24_out),
    .pixbuf_y_val_V_24_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_24_out_ap_vld),
    .pixbuf_y_val_V_23_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_23_out),
    .pixbuf_y_val_V_23_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_23_out_ap_vld),
    .pixbuf_y_val_V_22_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_22_out),
    .pixbuf_y_val_V_22_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_22_out_ap_vld),
    .pixbuf_y_val_V_21_out_i(pixbuf_y_val_V_15_fu_114),
    .pixbuf_y_val_V_21_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_21_out_o),
    .pixbuf_y_val_V_21_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_21_out_o_ap_vld),
    .pixbuf_y_val_V_20_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_20_out),
    .pixbuf_y_val_V_20_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_20_out_ap_vld),
    .p_0_0_0_0_0_21063_out_i(p_0_0_0_0_0_21061_lcssa1087_fu_106),
    .p_0_0_0_0_0_21063_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0_21063_out_o),
    .p_0_0_0_0_0_21063_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0_21063_out_o_ap_vld),
    .p_0_0_0_0_0511_21060_out_i(p_0_0_0_0_0511_21058_lcssa1084_fu_102),
    .p_0_0_0_0_0511_21060_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0511_21060_out_o),
    .p_0_0_0_0_0511_21060_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0511_21060_out_o_ap_vld),
    .p_out_i(p_lcssa10571081_fu_98),
    .p_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out_o),
    .p_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out_o_ap_vld),
    .p_out1_i(p_lcssa10561078_fu_94),
    .p_out1_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out1_o),
    .p_out1_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out1_o_ap_vld),
    .p_out2_i(p_lcssa10541072_fu_90),
    .p_out2_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out2_o),
    .p_out2_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out2_o_ap_vld),
    .p_out3_i(p_lcssa1066_fu_86),
    .p_out3_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out3_o),
    .p_out3_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out3_o_ap_vld),
    .p_0_1_0_0_01024_out_i(p_0_1_0_0_01021_lcssa1046_fu_82),
    .p_0_1_0_0_01024_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01024_out_o),
    .p_0_1_0_0_01024_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01024_out_o_ap_vld),
    .p_0_1_0_0_01020_out_i(p_0_1_0_0_01017_lcssa1043_fu_78),
    .p_0_1_0_0_01020_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01020_out_o),
    .p_0_1_0_0_01020_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01020_out_o_ap_vld),
    .p_0_2_0_0_01014_out_i(p_0_2_0_0_01013_lcssa1037_fu_70),
    .p_0_2_0_0_01014_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_2_0_0_01014_out_o),
    .p_0_2_0_0_01014_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_2_0_0_01014_out_o_ap_vld),
    .p_0_1_0_0_01012_out_i(p_0_1_0_0_01011_lcssa1034_fu_66),
    .p_0_1_0_0_01012_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01012_out_o),
    .p_0_1_0_0_01012_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01012_out_o_ap_vld),
    .p_0_0_0_0_05191010_out_i(p_0_0_0_0_05191009_lcssa1031_fu_62),
    .p_0_0_0_0_05191010_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_05191010_out_o),
    .p_0_0_0_0_05191010_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_05191010_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln1634_fu_226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_ready == 1'b1)) begin
            grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_58 <= 15'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        y_fu_58 <= y_4_reg_413;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cmp361000_reg_406 <= cmp361000_fu_214_p2;
        select_ln1632_reg_401[0] <= select_ln1632_fu_207_p3[0];
select_ln1632_reg_401[2] <= select_ln1632_fu_207_p3[2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        loopWidth_reg_386 <= loopWidth_fu_197_p2;
        trunc_ln1597_reg_391 <= trunc_ln1597_fu_203_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0511_21060_out_o_ap_vld == 1'b1))) begin
        p_0_0_0_0_0511_21058_lcssa1084_fu_102 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0511_21060_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_05191010_out_o_ap_vld == 1'b1))) begin
        p_0_0_0_0_05191009_lcssa1031_fu_62 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_05191010_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((cmp361000_reg_406 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        p_0_0_0_0_05191015_lcssa1040_fu_74 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_20_out;
        pixbuf_y_val_V_fu_110 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_20_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0_21063_out_o_ap_vld == 1'b1))) begin
        p_0_0_0_0_0_21061_lcssa1087_fu_106 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_0_0_0_0_21063_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01012_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_01011_lcssa1034_fu_66 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01012_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01020_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_01017_lcssa1043_fu_78 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01020_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01024_out_o_ap_vld == 1'b1))) begin
        p_0_1_0_0_01021_lcssa1046_fu_82 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_1_0_0_01024_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_2_0_0_01014_out_o_ap_vld == 1'b1))) begin
        p_0_2_0_0_01013_lcssa1037_fu_70 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_0_2_0_0_01014_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out2_o_ap_vld == 1'b1))) begin
        p_lcssa10541072_fu_90 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out1_o_ap_vld == 1'b1))) begin
        p_lcssa10561078_fu_94 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out_o_ap_vld == 1'b1))) begin
        p_lcssa10571081_fu_98 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out3_o_ap_vld == 1'b1))) begin
        p_lcssa1066_fu_86 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_p_out3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_21_out_o_ap_vld == 1'b1))) begin
        pixbuf_y_val_V_15_fu_114 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_21_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_22_out_ap_vld == 1'b1))) begin
        pixbuf_y_val_V_16_fu_118 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_22_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1634_fu_226_p2 == 1'd1) & (cmp361000_reg_406 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        pixbuf_y_val_V_16_load_reg_418 <= pixbuf_y_val_V_16_fu_118;
        pixbuf_y_val_V_17_load_reg_423 <= pixbuf_y_val_V_17_fu_122;
        pixbuf_y_val_V_18_load_reg_428 <= pixbuf_y_val_V_18_fu_126;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_23_out_ap_vld == 1'b1))) begin
        pixbuf_y_val_V_17_fu_122 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_23_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_24_out_ap_vld == 1'b1))) begin
        pixbuf_y_val_V_18_fu_126 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_pixbuf_y_val_V_24_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        y_4_reg_413 <= y_4_fu_231_p2;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1634_fu_226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1634_fu_226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        stream_in_read = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_in_read;
    end else begin
        stream_in_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        stream_upsampled_write = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_upsampled_write;
    end else begin
        stream_upsampled_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln1634_fu_226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln1634_fu_226_p2 == 1'd1) & (cmp361000_reg_406 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp361000_fu_214_p2 = (($signed(loopWidth_reg_386) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_ap_start_reg;

assign icmp_ln1634_fu_226_p2 = (($signed(zext_ln1634_fu_222_p1) < $signed(Height)) ? 1'b1 : 1'b0);

assign loopWidth_fu_197_p2 = (WidthIn + select_ln1632_2_fu_190_p3);

assign select_ln1632_2_fu_190_p3 = ((p_read[0:0] == 1'b1) ? 16'd0 : 16'd5);

assign select_ln1632_fu_207_p3 = ((p_read[0:0] == 1'b1) ? 3'd0 : 3'd5);

assign stream_upsampled_din = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_1636_2_fu_152_stream_upsampled_din;

assign trunc_ln1597_fu_203_p1 = loopWidth_fu_197_p2[14:0];

assign y_4_fu_231_p2 = (y_fu_58 + 15'd1);

assign zext_ln1634_fu_222_p1 = y_fu_58;

always @ (posedge ap_clk) begin
    select_ln1632_reg_401[1] <= 1'b0;
end

endmodule //bd_3a92_hsc_0_v_hcresampler_core
