
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_width_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_height_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_video_format_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_col_start_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_col_end_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_row_start_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_row_end_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_Y_R_value_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_Cb_G_value_reg[*]]
#set_false_path -from [get_cells v_letterbox_CTRL_s_axi_U/int_HwReg_Cr_B_value_reg[*]]

set_false_path -from [get_cells CTRL_s_axi_U/int_width_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_height_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_video_format_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_col_start_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_col_end_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_row_start_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_row_end_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_Y_R_value_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_Cb_G_value_reg[*]]
set_false_path -from [get_cells CTRL_s_axi_U/int_Cr_B_value_reg[*]]
